version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine: True
    steps:
      - checkout
      - run:
          command: docker-compose run app sh -c "python manage.py test && flake8"
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
